type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Project @table {
  name: String!
  createdAt: Timestamp!
  description: String
  user: User
}

type Task @table {
  title: String!
  createdAt: Timestamp!
  isCompleted: Boolean!
  priority: String! # Could also be an enum if enums were supported
  description: String
  dueDate: Date
  completedAt: Timestamp
  user: User
  project: Project
}